version: 2.1

commands:
  print_pipeline_id:
    description: "prints the Circle CI Workflow ID"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  my_job:
    docker: 
      - image: cimg/base:stable
    steps:
      - print_pipeine_id

     
workflows:
  print-hello-world-workflow:
    jobs:
      - my_job

