version: 2.1

jobs:
  save-hello-world-output:
    docker: 
      - image: cimg/base:stable
    steps:
      - run:
        comand: echo "hello world!" > output.txt
      - persist-to-workspace:
        root: /tmp/workspace
        paths: 
          - output.txt

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach-workspace:
        at: /tmp/workspace
      - run:  
        command: "cat output.txt"
        
     
workflows:
  print-hello-world-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-my-name:
          requires:
            - print-hello
            - print-world
