version: 2.1

jobs:
  save_hello_world_output:
    docker: 
      - image: cimg/base:stable
    steps:
      - run:
          command: echo "hello world!" > output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - run:  
          command: "cat output.txt"

     
workflows:
  print-hello-world-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
