version: 2.1

jobs:
  my_job:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1
      - run: 
          name: on error
          command: echo "Job failed with error code 1"
          when: on_fail
   
workflows:
  print-hello-world-workflow:
    jobs:
      - my_job

